### PR TITLE
Add constructor that accepts an array of registration keys.

### PR DESCRIPTION
**Pull request by dfdemar**

### CODE REVIEW

**Comment by dfdemar** [comment]
@coladict, please take a look when you get the chance. Feel free to merge this into master if you think it looks good.

**Comment by coladict** [comment]
Hey, sorry I forgot about this. What keys customizations would necessitate this? I took effort to make the library plug-and-play, hoping things like this wouldn't be necessary.

**Comment by coladict** [comment]
Added version 1.3 with a lot more configuration options than just that. You can now change this configuration option and just about every other one. It's described in the README and documented in the javadoc.

**Comment by dfdemar** [comment]
@coladict - I have an alternative solution that might be preferable to the changes in this pull request. When I have some free time I'll make a new PR with those changes, along with a better description of the problem I'm trying to solve.

**Pull request closed without merging**
